apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::070822278665:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-86CN1VB4BQDO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::070822278665:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-07T13:26:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1589"
  uid: c6a72c88-e9f4-46d9-a1d2-d6df8cb5d87b
